"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserModel = exports.TweetModel = exports.CommentModel = void 0;
const typegoose_1 = require("@typegoose/typegoose");
const comment_schema_1 = require("./comment.schema");
const user_schema_1 = require("./user.schema");
const tweet_schema_1 = require("./tweet.schema");
exports.CommentModel = (0, typegoose_1.getModelForClass)(comment_schema_1.Comment);
exports.TweetModel = (0, typegoose_1.getModelForClass)(tweet_schema_1.Tweet);
exports.UserModel = (0, typegoose_1.getModelForClass)(user_schema_1.User);
